language: python

python:
  - "2.7"

branches:
  only:
  - master
  - dev
  - adding-tests
  - API-Tests

notifications:
  email: false

# Using packages downloaded
virtualenv:
  system_site_packages: true

env: 
  - DJANGO_VERSION=1.11.11

before-install:
  - python -m pip install --upgrade pip

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install django-tastypie

script:
  python manage.py test RPL/tests