language: python

python:
  - "2.7"

branches:
  only:
  - master
  - dev

notifications:
  email: false

# Using packages downloaded
virtualenv:
  system_site_packages: true

env: 
  - DJANGO_VERSION=1.11.11

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install coreapi

script:
  # - ./manage.py test