language: python

python:
  - "2.7"

notifications:
  email: false

# Using packages downloaded
virtualenv:
  system_site_packages: true

env: 
  - DJANGO_VERSION=1.11.11

before-install:
  - python -m pip install --upgrade pip

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install django-tastypie
  - pip install django-cors-headers

before_script:
  - cd Control-Server/server/remote_physics_lab/
  - python manage.py makemigrations
  - python manage.py migrate

script:
  python manage.py test RPL/tests --verbosity=3